# Ejercicio 1: Slicing y Sub-matrices

In [27]:
import numpy as np
lista = np.arange(1, 26).reshape(5, -1)

matrizCentral = lista[1:4, 1:4]

ultimaColumna = lista[0:6, 4:5]

print(f"Lista: {lista} \n")
print(f"Matriz central: {matrizCentral} \n")
print(f"Utlima columna: {ultimaColumna} \n")

Lista: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

Matriz central: [[ 7  8  9]
 [12 13 14]
 [17 18 19]] 

Utlima columna: [[ 5]
 [10]
 [15]
 [20]
 [25]] 



# Ejercicio 2: Estadísticas con Ejes (Axis)

In [31]:
import numpy as np

ventas = np.array([
  [1500, 2000, 1800, 2200],
  [1100, 1300, 1200, 1500],
  [3000, 3100, 2900, 3500]
])

totalVentas = ventas.sum()

promedioSemanal = ventas.mean(axis=0)

maximoSucursal = ventas.max(axis=1)

print(f"Total ventas: {totalVentas}\n")
print(f"Promedio semanal: {promedioSemanal}\n")
print(f"Maxipo por sucursal: {maximoSucursal}\n")


Total ventas: 25100

Promedio semanal: [1866.66666667 2133.33333333 1966.66666667 2400.        ]

Maxipo por sucursal: [2200 1500 3500]



# Ejercicio 3: El poder de la Máscara Booleana

In [ ]:
import numpy as np

array = np.arange(1, 21)

mascara = array % 2 == 0

numerosPares = array[mascara]

print(f"Mascara: {mascara}")
print(f"Numeros pares: {numerosPares}")

Mascara: [False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]
Numero pares: [ 2  4  6  8 10 12 14 16 18 20]


# Ejercicio 4: Condiciones Múltiples (El Analista de RRHH)

In [36]:
import numpy as np

edades = np.array([22, 55, 34, 19, 45, 61, 28, 30, 42])

mascara = (edades >= 30) & (edades <=50)
mascaraExtremos = (edades < 25) | (edades > 55)

trabajadoresFiltrados = edades[mascara]
trabajadoresFiltradosExtremos = edades[mascaraExtremos]

print(f"Trabajadores entre 30 y 50 años: {trabajadoresFiltrados}")
print(f"Trabajadores menores de 25 O mayores de 55 años: {trabajadoresFiltradosExtremos}")

Trabajadores entre 30 y 50 años: [34 45 30 42]
Trabajadores menores de 25 O mayores de 55 años: [22 19 61]


# Ejercicio 5: Modificación Condicional

In [47]:
import numpy as np

matriz = np.zeros((4, 4), dtype=int)
print(f"Matriz original: \n{matriz}\n")

matriz[1:3, 1:3] = 9
print(f"Matriz actualizada: \n{matriz}\n")



Matriz original: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matriz actualizada: 
[[0 0 0 0]
 [0 9 9 0]
 [0 9 9 0]
 [0 0 0 0]]



# Ejercicio 6: Desafío Integrador "El Profesor Robot"

In [58]:
import numpy as np

calificaciones = np.random.randint(1, 11, 50)
print(f"Calificaciones: {calificaciones}")

promedio = calificaciones.mean()
print(f"Promedio: {promedio}")

mascaraDesaprobados = calificaciones < 4

totalDesaprobados = calificaciones[mascaraDesaprobados].size
print(f"Total desaprobados: {totalDesaprobados}")

calificaciones[mascaraDesaprobados] = 4

print(f"Calificaciones actualizdas: {calificaciones}")

Calificaciones: [ 3 10  1  1 10 10  5  9  5  5  8  6  9  9 10  1  6 10  4  5  9  2  5  4
  4  1  7  8  4  8  2  9  3  5  4  6 10  3  9  3  1  1  9  7  8  8  9  6
  1  2]
Promedio: 5.7
Total desaprobados: 14
Calificaciones actualizdas: [ 4 10  4  4 10 10  5  9  5  5  8  6  9  9 10  4  6 10  4  5  9  4  5  4
  4  4  7  8  4  8  4  9  4  5  4  6 10  4  9  4  4  4  9  7  8  8  9  6
  4  4]
