# Ejercicio 1: Creación y Atributos

In [3]:
import numpy

lista = numpy.array([1, 2, 3, 4, 5])
print(f"Dimensión: {lista.ndim}")
print(f"Forma: {lista.shape}")
print(f"tipo: {lista.dtype}")
lista_float = lista.astype(float)
print(f"tipo: {lista_float.dtype}")


Dimensión: 1
Forma: (5,)
tipo: int64
tipo: float64


# Ejercicio 2: Secuencias Automáticas


In [12]:
import numpy
ids_clientes = numpy.arange(1, 101, 1)
print(ids_clientes)

puntos_grafico = numpy.linspace(0, 10, 50);
print(puntos_grafico)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591

# Ejercicio 3: Matrices y Datos Aleatorios

In [1]:
import numpy
matriz = numpy.random.rand(3, 4)
print(matriz)

matrizDeUno = numpy.ones((3, 4), dtype=int)
print(matrizDeUno)

[[0.92667391 0.71460914 0.78497392 0.04835337]
 [0.89059887 0.56632315 0.48745122 0.29681593]
 [0.18963268 0.49136725 0.0370546  0.95486351]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Ejercicio 4: El Simulador de Inventario (Integración)

In [3]:
import numpy as np
cantidadSucursales = int(input("Ingrese la cantidad de sucursales: "))
cantidadProductos = int(input("Ingrese la cantidad de productos: "))

matriz = np.zeros((cantidadSucursales, cantidadProductos), dtype=int)
print(matriz)
print("Base de datos de inventario inicializada correctamente")


[[0 0 0 0 0]
 [0 0 0 0 0]]
Base de datos de inventario inicializada correctamente


# Ejercicio 5: Redimensionando la realidad (Reshape)

In [15]:
import numpy as np

array = np.arange(1, 13)
print(array.ndim)

newArray = np.reshape(array, (3, 4))

print(newArray.ndim)

1
2


# Ejercicio 6: El peso de los datos (Optimización)

In [ ]:
import numpy as np

array = np.array([25.5, 28.1, 22.4, 19.9, 30.2])
print(array)
print(array.dtype)

newArray = array.astype(int)
print(newArray)
print(newArray.dtype)

[25.5 28.1 22.4 19.9 30.2]
float64
[25 28 22 19 30]
int64


# Ejercicio 7: Simulador de Dados (Números Aleatorios Enteros)

In [26]:
import numpy as np

dados = np.random.randint(1, 7, 10)
print(dados)

[6 3 1 1 3 5 2 3 6 3]


# Ejercicio 8: Limpieza de sensores (Conversión desde texto)

In [31]:
import numpy as np

datosCrudos =  np.array(["45.2", "48.1", "42.5", "50.0"])
print(datosCrudos.dtype)
print(datosCrudos)

datosEnteros = datosCrudos.astype(float)

print(datosEnteros.dtype)
print(datosEnteros)

<U4
['45.2' '48.1' '42.5' '50.0']
float64
[45.2 48.1 42.5 50. ]


# Ejercicio 9: La Matriz Identidad y un pequeño "spoiler"

In [33]:
import numpy as np

matriz = np.eye(4)
print(matriz)

nuevoDato = matriz * 5
print(nuevoDato)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]
